# Clippy configuration

# Specific lint configurations
avoid-breaking-exported-api = false
cognitive-complexity-threshold = 30
max-struct-bools = 3
type-complexity-threshold = 250
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
trivial-copy-size-limit = 8