# Rust formatting configuration

# Baseline formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports and modules
reorder_imports = true
reorder_modules = true

# Shorthand preferences
use_field_init_shorthand = true
use_try_shorthand = true